"""
Contract layer between backend and frontend agents.

Generates and maintains TypeScript type definitions and API route
constants that both agents import from. This is the shared interface
that keeps backend and frontend in sync.

Contracts are defined in config.py SPRINT_CONTRACTS dict.
"""

import subprocess
from pathlib import Path
from config import SPRINT_CONTRACTS, CONSTANTS_TS


def generate_contract_skeleton(sprint_num: int, repo_dir: Path):
    """Generate or update the contract files for a sprint.

    Builds cumulative types and routes from Sprint 1 through the
    current sprint, then writes three files:
      - src/contracts/api-types.ts   (all TypeScript interfaces)
      - src/contracts/api-routes.ts  (route constants)
      - src/contracts/constants.ts   (shared business constants)
    """
    contracts_dir = repo_dir / "src" / "contracts"
    contracts_dir.mkdir(parents=True, exist_ok=True)

    # Build cumulative types and routes from all sprints up to current
    all_types: dict[str, str] = {}
    all_routes: dict[str, dict] = {}

    for s in range(1, sprint_num + 1):
        if s in SPRINT_CONTRACTS:
            contract = SPRINT_CONTRACTS[s]
            all_types.update(contract.get("types", {}))
            for domain, routes in contract.get("routes", {}).items():
                if domain not in all_routes:
                    all_routes[domain] = {}
                all_routes[domain].update(routes)

    # -- Write api-types.ts --
    types_lines = [
        "// AUTO-GENERATED by Dual-Agent Builder",
        "// Both backend (API routes) and frontend (fetch calls) import from this file",
        "// DO NOT edit manually -- updated after each backend sprint",
        "",
        "// === Response Envelope ===",
        "export interface ApiResponse<T> {",
        "  data: T;",
        "}",
        "",
        "export interface ApiError {",
        "  error: string;",
        "  code: string;",
        "}",
        "",
    ]
    for type_name, type_def in all_types.items():
        types_lines.append(f"// === {type_name} ===")
        types_lines.append(type_def)
        types_lines.append("")

    (contracts_dir / "api-types.ts").write_text("\n".join(types_lines))

    # -- Write api-routes.ts --
    routes_lines = [
        "// AUTO-GENERATED by Dual-Agent Builder",
        "// Single source of truth for all API endpoints",
        "// Frontend uses these for fetch URLs. Backend uses these for route registration.",
        "",
        "export const API_ROUTES = {",
    ]
    for domain, routes in all_routes.items():
        routes_lines.append(f"  {domain}: {{")
        for name, route_config in routes.items():
            method = route_config["method"]
            path = route_config["path"]
            auth = "true" if route_config["auth"] else "false"
            routes_lines.append(
                f"    {name}: {{ method: '{method}', path: '{path}', auth: {auth} }},"
            )
        routes_lines.append("  },")
    routes_lines.append("} as const;")
    routes_lines.append("")
    routes_lines.append("export type ApiRouteDomain = keyof typeof API_ROUTES;")
    routes_lines.append("")

    (contracts_dir / "api-routes.ts").write_text("\n".join(routes_lines))

    # -- Write constants.ts --
    (contracts_dir / "constants.ts").write_text(CONSTANTS_TS)


def update_contracts_after_backend(sprint_num: int, repo_dir: Path):
    """Update contracts after the backend sprint completes.

    Re-generates the contract files and optionally runs Supabase
    type generation if the CLI is available.
    """
    generate_contract_skeleton(sprint_num, repo_dir)

    # Try to generate Supabase types if the CLI is available
    try:
        result = subprocess.run(
            ["supabase", "gen", "types", "typescript", "--local"],
            cwd=str(repo_dir),
            capture_output=True,
            text=True,
            timeout=30
        )
        if result.returncode == 0 and result.stdout.strip():
            db_types_file = repo_dir / "src" / "contracts" / "db-types.ts"
            db_types_file.write_text(
                f"// AUTO-GENERATED by supabase gen types\n{result.stdout}"
            )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass  # Supabase types generation is optional
