#!/usr/bin/env bash
#
# Setup Ralph Supervision for a Dual-Agent Builder project.
#
# Usage:
#   .buildrunner/setup_ralph.sh /path/to/project
#   .buildrunner/setup_ralph.sh  (uses current directory)
#
# This creates the .ralph/ directory and .ralphrc in the target project,
# configured to monitor the autonomous pipeline every 5 minutes.
#

set -euo pipefail

PROJECT_DIR="${1:-$(pwd)}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILDER_DIR="$(dirname "$SCRIPT_DIR")"

echo "Setting up Ralph supervision for: $PROJECT_DIR"

# Verify it's a dual-agent-builder project
if [ ! -d "$PROJECT_DIR/.buildrunner" ]; then
    echo "ERROR: $PROJECT_DIR/.buildrunner not found."
    echo "This doesn't look like a dual-agent-builder project."
    exit 1
fi

# Verify Ralph is installed
if ! command -v ralph &>/dev/null; then
    echo "ERROR: Ralph not found. Install first:"
    echo "  git clone https://github.com/frankbria/ralph-claude-code.git"
    echo "  cd ralph-claude-code && ./install.sh"
    exit 1
fi

# Create .ralph directory
mkdir -p "$PROJECT_DIR/.ralph/specs"
mkdir -p "$PROJECT_DIR/.ralph/logs"

# Get product name from autonomous state if available
PRODUCT_NAME="Unknown"
if [ -f "$PROJECT_DIR/.buildrunner/.autonomous-state" ]; then
    PRODUCT_NAME=$(python3 -c "import json; print(json.load(open('$PROJECT_DIR/.buildrunner/.autonomous-state')).get('product_name', 'Unknown'))" 2>/dev/null || echo "Unknown")
fi

# Write PROMPT.md with project directory injected
sed "s|{PROJECT_DIR}|$PROJECT_DIR|g" "$BUILDER_DIR/.ralph/PROMPT.md" > "$PROJECT_DIR/.ralph/PROMPT.md"
echo "  Created .ralph/PROMPT.md (supervisor prompt)"

# Write AGENT.md with project directory injected
sed "s|{PROJECT_DIR}|$PROJECT_DIR|g" "$BUILDER_DIR/.ralph/AGENT.md" > "$PROJECT_DIR/.ralph/AGENT.md"
echo "  Created .ralph/AGENT.md (build/test/recovery commands)"

# Copy fix_plan.md
cp "$BUILDER_DIR/.ralph/fix_plan.md" "$PROJECT_DIR/.ralph/fix_plan.md"
echo "  Created .ralph/fix_plan.md (supervisor task list)"

# Write .ralphrc with project-specific config
cat > "$PROJECT_DIR/.ralphrc" << RALPHRC
# Ralph Supervisor Configuration — $PRODUCT_NAME
# Auto-generated by setup_ralph.sh

PROJECT_NAME="${PRODUCT_NAME}-supervisor"
PROJECT_TYPE="python"
MAX_CALLS_PER_HOUR=12
CLAUDE_TIMEOUT_MINUTES=10
CLAUDE_OUTPUT_FORMAT=json
SESSION_CONTINUITY=true
SESSION_EXPIRY_HOURS=24
CB_NO_PROGRESS_THRESHOLD=6
CB_SAME_ERROR_THRESHOLD=5
CB_COOLDOWN_MINUTES=15
CB_AUTO_RESET=true
ALLOWED_TOOLS="Read Write Edit Bash(cd *) Bash(python3 *) Bash(cat *) Bash(tail *) Bash(head *) Bash(git *) Bash(kill *) Bash(ps *) Bash(nohup *) Bash(echo *) Bash(sleep *)"
RALPH_VERBOSE=true
RALPHRC
echo "  Created .ralphrc (12 calls/hour = every 5 min)"

# Write .gitignore additions
if [ -f "$PROJECT_DIR/.gitignore" ]; then
    if ! grep -q ".ralph/logs" "$PROJECT_DIR/.gitignore"; then
        echo -e "\n# Ralph supervisor\n.ralph/logs/\n.ralph/.call_count\n.ralph/.last_reset\n.ralph/.exit_signals\n.ralph/.response_analysis\n.ralph/.circuit_breaker_state\n.ralph/.ralph_session\n.ralph/.claude_session_id\n.ralph/live.log\n.ralph/status.json\n.ralph/progress.json" >> "$PROJECT_DIR/.gitignore"
    fi
else
    cat > "$PROJECT_DIR/.gitignore" << 'GITIGNORE'
# Ralph supervisor
.ralph/logs/
.ralph/.call_count
.ralph/.last_reset
.ralph/.exit_signals
.ralph/.response_analysis
.ralph/.circuit_breaker_state
.ralph/.circuit_breaker_history
.ralph/.ralph_session
.ralph/.ralph_session_history
.ralph/.claude_session_id
.ralph/.loop_start_sha
.ralph/live.log
.ralph/status.json
.ralph/progress.json
GITIGNORE
fi
echo "  Updated .gitignore"

echo ""
echo "Ralph supervision ready for $PRODUCT_NAME!"
echo ""
echo "Start monitoring:"
echo "  cd $PROJECT_DIR && ralph --monitor"
echo ""
echo "Or headless:"
echo "  cd $PROJECT_DIR && ralph --verbose"
echo ""
echo "Check status:"
echo "  cd $PROJECT_DIR && ralph --status"
